dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install cpp-coveralls

install:
  - sudo apt-get install -qq cmake gcc-8 can-utils g++-8 libnet1-dev libtool libssl-dev libjansson-dev autogen make wget unzip libtool can-utils valgrind
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
  - git clone https://github.com/hartkopp/can-isotp.git
  - cd can-isotp
  - sudo apt-get install build-essential linux-headers-$(uname -r)
  - make
  - sudo make modules_install
  - sudo modprobe can vcan
  - sudo insmod ./net/can/can-isotp.ko
  - cd ..
  - wget https://github.com/libuv/libuv/archive/v1.25.0.zip
  - unzip v1.25.0.zip
  - cd libuv-1.25.0
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - git submodule init
  - git submodule update
  - cd ..
  - sudo sh -c 'echo /usr/local/lib >> /etc/ld.so.conf'
  - sudo ldconfig


language: cpp

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ../ -DCOVERAGE=1
  - cmake --build .
  #- valgrind --tool=memcheck --xml=yes --xml-file=./valgrind.xml --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./Test  --gtest_filter=-` tr '\n' ':' < ../tests/travis.excludes`
  - ./Test  --gtest_filter=-` tr '\n' ':' < ../tests/travis.excludes`

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"