dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake gcc-8 can-utils g++-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
  - git clone https://github.com/hartkopp/can-isotp.git
  - cd can-isotp
  - sudo apt-get install build-essential linux-headers-$(uname -r)
  - make
  - sudo make modules_install
  - modprobe can
  - insmod ./net/can/can-isotp.ko

language: cpp

compiler:
  - gcc


script:
- mkdir build
- cd build
- cmake ../
- cmake --build .
- ../createAdapter.sh
- ./Test
